name: Test Go For Range Check Action
on:
  push:
    branches: ["test", "main", "master"]
    tags: ["test*"]

jobs:
  go-for-range-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'


      - name: Run Go For Range Check Action
        uses: xuanskyer/go-for-range-check-action@v1.0.15
        with:
          max-for-range-level: '3'
          target-directory: 'biz'
          ignore-directory: '[\"vendor\"]'


